image_width: 1280
image_height: 1024
camera_name: hik_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [1174.53533,    0.     ,  573.72016,
            0.     , 1174.54976,  537.19688,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.130552, 0.092792, -0.000685, 0.000438, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1135.75708,    0.     ,  570.5891 ,    0.     ,
            0.     , 1146.92419,  537.15958,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
