# UI数据

Header header

# 图层数,范围0-9
int32 layer

rm_referee_controller/WidgetArc[] arcs
rm_referee_controller/WidgetCircle[] circles
rm_referee_controller/WidgetFloatNumber[] floatNumbers
rm_referee_controller/WidgetIntNumber[] intNumbers
rm_referee_controller/WidgetLine[] lines
rm_referee_controller/WidgetOval[] ovals
rm_referee_controller/WidgetRectangle[] rectangles
rm_referee_controller/WidgetString[] strings