# UI Oval组件

# ID
int32 id
# 是否隐藏该组件
bool hide
# 是否强制刷新
bool isForceUpdate
# 图形颜色
uint8 color
# 红蓝主色
uint8 COLOR_RED_BLUE  = 0
# 黄色
uint8 COLOR_YELLOW    = 1
# 绿色
uint8 COLOR_GREEN     = 2
# 橙色
uint8 COLOR_ORANGE    = 3
# 紫红色
uint8 COLOR_FUCHSIA   = 4
# 粉色
uint8 COLOR_PINK      = 5
# 青色
uint8 COLOR_CYAN_BLUE = 6
# 黑色
uint8 COLOR_BLACK     = 7
# 白色
uint8 COLOR_WHITE     = 8
# 线条宽度
int32 width
# 圆心X坐标
int32 centerX
# 圆心Y坐标
int32 centerY
# X半轴长
int32 xRadius
# Y半轴长
int32 yRadius