# UI FloatNumber组件组件

# ID
int32 id
# 是否隐藏该组件
bool hide
# 图形颜色
uint8 color
# 红蓝主色
uint8 COLOR_RED_BLUE  = 0
# 黄色
uint8 COLOR_YELLOW    = 1
# 绿色
uint8 COLOR_GREEN     = 2
# 橙色
uint8 COLOR_ORANGE    = 3
# 紫红色
uint8 COLOR_FUCHSIA   = 4
# 粉色
uint8 COLOR_PINK      = 5
# 青色
uint8 COLOR_CYAN_BLUE = 6
# 黑色
uint8 COLOR_BLACK     = 7
# 白色
uint8 COLOR_WHITE     = 8
# 线条宽度
int32 width
# 起点X坐标
int32 startX
# 起点Y坐标
int32 startY
# 输出的数
float64 data
# 字体大小
int32 fontSize
# 小数点后位数
int32 digits